runtime: python38

instance_class: F1

env_variables:
  MYSQL_USER: 'flask'
  MYSQL_PASSWORD: 'flask'
  MYSQL_DB: 'todo'
  # MYSQL_HOST: <database_ip>

handlers:
- url: /img
  static_dir: static/img

- url: /script
  static_dir: static/script

- url: /styles
  static_dir: static/styles
