runtime: python38

instance_class: F1

env_variables:
  MYSQL_USER: 'flask'
  MYSQL_PASSWORD: 'root'
  MYSQL_DB: 'todo'
  MYSQL_HOST: 10.47.16.3

handlers:
- url: /img
  static_dir: static/img

- url: /script
  static_dir: static/script

- url: /styles
  static_dir: static/styles
