version: "3"
services:
  # app:
  #   platform: linux/amd64
  #   build: .
  #   ports:
  #     - "5001:5001"
  #   container_name: flask_app
  #   environment:
  #     FLASK_APP: "app/app.py"
  #     FLASK_ENV: "development"
  #   command: "flask run --host=0.0.0.0 --port=5001"

  web:
    platform: linux/amd64
    build: ./flask
    volumes:
      - ./flask:/app
    ports:
      - 5000:5000
    links:
      - db
    tty: true

  db:
    platform: linux/amd64
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: flask
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
      - ./db/log:/var/log/mysql
    ports:
      - 3306:3306
